api:
  source: polygon
  timezone: America/New_York
session:
  start: "09:30"
  end: "16:00"
thresholds:
  equal_tolerance_atr: 0.05
  bos_buffer_atr: 0.1
  stop_buffer_atr: 0.05
weights:
  clean_fvg: 25
  fvg_size: 20
  liquidity_proximity: 20
  rvol: 15
  vwap_confluence: 10
  session_quality: 10
options:
  exclude_lunch: true
